### ISSUE TITLE
Error: fork/exec /var/task/bootstrap: exec format error

### ISSUE THREAD

**Issue by benzdeus** [ShawnOY/go-serverless-api-example#1]
Error: fork/exec /var/task/bootstrap: exec format error

i use windows 11
Step
set GOOS=linux 
set GOARCH=arm64
go build -o bootstrap main.go
zipfile

-------------

SET ENV GIN_MODE

-------------
HandlerInfo
bootstrap

-------------
TEST

Result: Error: fork/exec /var/task/bootstrap: exec format error
Runtime.InvalidEntrypoint

**Comment by ShawnOY** [comment]
Hi @benzdeus 
I guess you run the binary file directly, if you wish to run the code on Windows, you have to change the environment variables, maybe you can try to use `set GOOD=windows` and `set GOARCH=amd64` .

In other hand, run `go run main.go` .

**Comment by ShawnOY** [comment]
Close the issue.
